# Generated by Django 6.0.7 on 2026-07-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование команды', max_length=250, unique=True, verbose_name='Наименование команды')),
                ('score', models.IntegerField(default=0, help_text='Набранные очки', verbose_name='Набранные очки')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ('name',),
            },
        ),
    ]
