# Generated by Django 6.0.7 on 2026-07-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_block_quiz_question_answeroption_block_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-score', 'name'), 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
    ]
