# Generated by Django 6.0.7 on 2026-07-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, help_text='Для ведущего: правильный вариант', max_length=500, verbose_name='Правильный ответ'),
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
    ]
