# Generated by Django 6.0.7 on 2026-07-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_answer_delete_answeroption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBlockResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Раунд проверен')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Время проверки')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_results', to='quiz.block')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_results', to='quiz.team')),
            ],
            options={
                'verbose_name': 'Результат команды в раунде',
                'verbose_name_plural': 'Результаты команд в раундах',
                'unique_together': {('team', 'block')},
            },
        ),
        migrations.CreateModel(
            name='AnswerMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Ответ верный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='quiz.teamblockresult')),
            ],
            options={
                'verbose_name': 'Отметка ответа',
                'verbose_name_plural': 'Отметки ответов',
                'unique_together': {('result', 'question')},
            },
        ),
    ]
