# Generated by Django 6.0.7 on 2026-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_teamblockresult_answermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamblockresult',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущий вопрос'),
        ),
    ]
