# Generated by Django 6.0.7 on 2026-08-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_teamblockresult_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamblockresult',
            name='block_score',
            field=models.IntegerField(default=0, verbose_name='Очки за раунд'),
        ),
    ]
