# Generated by Django 6.0.7 on 2026-08-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_teamblockresult_block_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание задания')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Task_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Текст вопроса')),
                ('answer', models.CharField(blank=True, help_text='Для ведущего: правильный вариант', max_length=250, verbose_name='Правильный ответ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='quiz.task')),
            ],
            options={
                'verbose_name': 'Вопросы задачи',
                'verbose_name_plural': 'Вопросы задачи',
            },
        ),
    ]
