# Generated by Django 6.0.7 on 2026-08-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_task_task_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
