# Generated by Django 6.0.7 on 2026-08-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_task_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='quiz.quiz', verbose_name='Связана с квизом'),
        ),
    ]
