# Generated by Django 6.0.7 on 2026-09-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_task_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img', verbose_name='Картинка'),
        ),
    ]
